<?php
/**
 * MODEL2eaa59
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * olist-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * MODEL2eaa59 Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MODEL2eaa59 implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'MODEL2eaa59';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'attributes' => 'string[]',
        'brand' => 'string',
        'categories' => 'string[]',
        'description' => 'string',
        'free_shipping' => 'bool',
        'group' => 'string',
        'gtin' => 'string',
        'name' => 'string',
        'package_measures' => 'string[]',
        'photos' => 'string[]',
        'prices' => 'string[]',
        'product_code' => 'string',
        'product_measures' => 'string[]',
        'seller_id' => 'string',
        'status' => 'string',
        'stock' => 'string[]',
        'tags' => 'string[]',
        'tax_informations' => 'object'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'attributes' => 'attributes',
        'brand' => 'brand',
        'categories' => 'categories',
        'description' => 'description',
        'free_shipping' => 'free_shipping',
        'group' => 'group',
        'gtin' => 'gtin',
        'name' => 'name',
        'package_measures' => 'package_measures',
        'photos' => 'photos',
        'prices' => 'prices',
        'product_code' => 'product_code',
        'product_measures' => 'product_measures',
        'seller_id' => 'seller_id',
        'status' => 'status',
        'stock' => 'stock',
        'tags' => 'tags',
        'tax_informations' => 'tax_informations'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'attributes' => 'setAttributes',
        'brand' => 'setBrand',
        'categories' => 'setCategories',
        'description' => 'setDescription',
        'free_shipping' => 'setFreeShipping',
        'group' => 'setGroup',
        'gtin' => 'setGtin',
        'name' => 'setName',
        'package_measures' => 'setPackageMeasures',
        'photos' => 'setPhotos',
        'prices' => 'setPrices',
        'product_code' => 'setProductCode',
        'product_measures' => 'setProductMeasures',
        'seller_id' => 'setSellerId',
        'status' => 'setStatus',
        'stock' => 'setStock',
        'tags' => 'setTags',
        'tax_informations' => 'setTaxInformations'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'attributes' => 'getAttributes',
        'brand' => 'getBrand',
        'categories' => 'getCategories',
        'description' => 'getDescription',
        'free_shipping' => 'getFreeShipping',
        'group' => 'getGroup',
        'gtin' => 'getGtin',
        'name' => 'getName',
        'package_measures' => 'getPackageMeasures',
        'photos' => 'getPhotos',
        'prices' => 'getPrices',
        'product_code' => 'getProductCode',
        'product_measures' => 'getProductMeasures',
        'seller_id' => 'getSellerId',
        'status' => 'getStatus',
        'stock' => 'getStock',
        'tags' => 'getTags',
        'tax_informations' => 'getTaxInformations'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['attributes'] = isset($data['attributes']) ? $data['attributes'] : null;
        $this->container['brand'] = isset($data['brand']) ? $data['brand'] : null;
        $this->container['categories'] = isset($data['categories']) ? $data['categories'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['free_shipping'] = isset($data['free_shipping']) ? $data['free_shipping'] : null;
        $this->container['group'] = isset($data['group']) ? $data['group'] : null;
        $this->container['gtin'] = isset($data['gtin']) ? $data['gtin'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['package_measures'] = isset($data['package_measures']) ? $data['package_measures'] : null;
        $this->container['photos'] = isset($data['photos']) ? $data['photos'] : null;
        $this->container['prices'] = isset($data['prices']) ? $data['prices'] : null;
        $this->container['product_code'] = isset($data['product_code']) ? $data['product_code'] : null;
        $this->container['product_measures'] = isset($data['product_measures']) ? $data['product_measures'] : null;
        $this->container['seller_id'] = isset($data['seller_id']) ? $data['seller_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['stock'] = isset($data['stock']) ? $data['stock'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['tax_informations'] = isset($data['tax_informations']) ? $data['tax_informations'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['attributes'] === null) {
            $invalid_properties[] = "'attributes' can't be null";
        }
        if ($this->container['brand'] === null) {
            $invalid_properties[] = "'brand' can't be null";
        }
        if ($this->container['categories'] === null) {
            $invalid_properties[] = "'categories' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalid_properties[] = "'description' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        if ($this->container['package_measures'] === null) {
            $invalid_properties[] = "'package_measures' can't be null";
        }
        if ($this->container['photos'] === null) {
            $invalid_properties[] = "'photos' can't be null";
        }
        if ($this->container['prices'] === null) {
            $invalid_properties[] = "'prices' can't be null";
        }
        if ($this->container['product_measures'] === null) {
            $invalid_properties[] = "'product_measures' can't be null";
        }
        if ($this->container['seller_id'] === null) {
            $invalid_properties[] = "'seller_id' can't be null";
        }
        if ($this->container['stock'] === null) {
            $invalid_properties[] = "'stock' can't be null";
        }
        if ($this->container['tags'] === null) {
            $invalid_properties[] = "'tags' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['attributes'] === null) {
            return false;
        }
        if ($this->container['brand'] === null) {
            return false;
        }
        if ($this->container['categories'] === null) {
            return false;
        }
        if ($this->container['description'] === null) {
            return false;
        }
        if ($this->container['name'] === null) {
            return false;
        }
        if ($this->container['package_measures'] === null) {
            return false;
        }
        if ($this->container['photos'] === null) {
            return false;
        }
        if ($this->container['prices'] === null) {
            return false;
        }
        if ($this->container['product_measures'] === null) {
            return false;
        }
        if ($this->container['seller_id'] === null) {
            return false;
        }
        if ($this->container['stock'] === null) {
            return false;
        }
        if ($this->container['tags'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets attributes
     * @return string[]
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     * @param string[] $attributes Category Attributes
     * @return $this
     */
    public function setAttributes($attributes)
    {
        $this->container['attributes'] = $attributes;

        return $this;
    }

    /**
     * Gets brand
     * @return string
     */
    public function getBrand()
    {
        return $this->container['brand'];
    }

    /**
     * Sets brand
     * @param string $brand Product brand
     * @return $this
     */
    public function setBrand($brand)
    {
        $this->container['brand'] = $brand;

        return $this;
    }

    /**
     * Gets categories
     * @return string[]
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     * @param string[] $categories Categories by channel urls
     * @return $this
     */
    public function setCategories($categories)
    {
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description Product Description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets free_shipping
     * @return bool
     */
    public function getFreeShipping()
    {
        return $this->container['free_shipping'];
    }

    /**
     * Sets free_shipping
     * @param bool $free_shipping Free shipping
     * @return $this
     */
    public function setFreeShipping($free_shipping)
    {
        $this->container['free_shipping'] = $free_shipping;

        return $this;
    }

    /**
     * Gets group
     * @return string
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     * @param string $group Group id as first sku added to this group
     * @return $this
     */
    public function setGroup($group)
    {
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets gtin
     * @return string
     */
    public function getGtin()
    {
        return $this->container['gtin'];
    }

    /**
     * Sets gtin
     * @param string $gtin Global Trade Item Number (Barcode)
     * @return $this
     */
    public function setGtin($gtin)
    {
        $this->container['gtin'] = $gtin;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Product name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets package_measures
     * @return string[]
     */
    public function getPackageMeasures()
    {
        return $this->container['package_measures'];
    }

    /**
     * Sets package_measures
     * @param string[] $package_measures Package volume measures
     * @return $this
     */
    public function setPackageMeasures($package_measures)
    {
        $this->container['package_measures'] = $package_measures;

        return $this;
    }

    /**
     * Gets photos
     * @return string[]
     */
    public function getPhotos()
    {
        return $this->container['photos'];
    }

    /**
     * Sets photos
     * @param string[] $photos Photos urls in JSON format
     * @return $this
     */
    public function setPhotos($photos)
    {
        $this->container['photos'] = $photos;

        return $this;
    }

    /**
     * Gets prices
     * @return string[]
     */
    public function getPrices()
    {
        return $this->container['prices'];
    }

    /**
     * Sets prices
     * @param string[] $prices Prices by channel
     * @return $this
     */
    public function setPrices($prices)
    {
        $this->container['prices'] = $prices;

        return $this;
    }

    /**
     * Gets product_code
     * @return string
     */
    public function getProductCode()
    {
        return $this->container['product_code'];
    }

    /**
     * Sets product_code
     * @param string $product_code Product code on seller side
     * @return $this
     */
    public function setProductCode($product_code)
    {
        $this->container['product_code'] = $product_code;

        return $this;
    }

    /**
     * Gets product_measures
     * @return string[]
     */
    public function getProductMeasures()
    {
        return $this->container['product_measures'];
    }

    /**
     * Sets product_measures
     * @param string[] $product_measures Product measures
     * @return $this
     */
    public function setProductMeasures($product_measures)
    {
        $this->container['product_measures'] = $product_measures;

        return $this;
    }

    /**
     * Gets seller_id
     * @return string
     */
    public function getSellerId()
    {
        return $this->container['seller_id'];
    }

    /**
     * Sets seller_id
     * @param string $seller_id Seller code
     * @return $this
     */
    public function setSellerId($seller_id)
    {
        $this->container['seller_id'] = $seller_id;

        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string $status Product status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets stock
     * @return string[]
     */
    public function getStock()
    {
        return $this->container['stock'];
    }

    /**
     * Sets stock
     * @param string[] $stock Stock with delivery time
     * @return $this
     */
    public function setStock($stock)
    {
        $this->container['stock'] = $stock;

        return $this;
    }

    /**
     * Gets tags
     * @return string[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     * @param string[] $tags Product Tags
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets tax_informations
     * @return object
     */
    public function getTaxInformations()
    {
        return $this->container['tax_informations'];
    }

    /**
     * Sets tax_informations
     * @param object $tax_informations Tax Informations
     * @return $this
     */
    public function setTaxInformations($tax_informations)
    {
        $this->container['tax_informations'] = $tax_informations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


