<?php
/**
 * MODELd4278cTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * olist-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MODELd4278cTest Class Doc Comment
 *
 * @category    Class */
// * @description MODELd4278c
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MODELd4278cTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MODELd4278c"
     */
    public function testMODELd4278c()
    {

    }

    /**
     * Test attribute "approved_at"
     */
    public function testPropertyApprovedAt()
    {

    }

    /**
     * Test attribute "availability_days"
     */
    public function testPropertyAvailabilityDays()
    {

    }

    /**
     * Test attribute "channel_slug"
     */
    public function testPropertyChannelSlug()
    {

    }

    /**
     * Test attribute "channel_store"
     */
    public function testPropertyChannelStore()
    {

    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {

    }

    /**
     * Test attribute "estimated_delivery_date"
     */
    public function testPropertyEstimatedDeliveryDate()
    {

    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {

    }

    /**
     * Test attribute "purchase_timestamp"
     */
    public function testPropertyPurchaseTimestamp()
    {

    }

    /**
     * Test attribute "seller_brand"
     */
    public function testPropertySellerBrand()
    {

    }

    /**
     * Test attribute "seller_email"
     */
    public function testPropertySellerEmail()
    {

    }

    /**
     * Test attribute "seller_id"
     */
    public function testPropertySellerId()
    {

    }

    /**
     * Test attribute "seller_name"
     */
    public function testPropertySellerName()
    {

    }

    /**
     * Test attribute "seller_order_items"
     */
    public function testPropertySellerOrderItems()
    {

    }

    /**
     * Test attribute "shipment"
     */
    public function testPropertyShipment()
    {

    }

    /**
     * Test attribute "shipping_limit_date"
     */
    public function testPropertyShippingLimitDate()
    {

    }

}
