<?php
/**
 * MODEL686451Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * olist-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MODEL686451Test Class Doc Comment
 *
 * @category    Class */
// * @description MODEL686451
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MODEL686451Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MODEL686451"
     */
    public function testMODEL686451()
    {

    }

    /**
     * Test attribute "about"
     */
    public function testPropertyAbout()
    {

    }

    /**
     * Test attribute "address_city"
     */
    public function testPropertyAddressCity()
    {

    }

    /**
     * Test attribute "address_complement"
     */
    public function testPropertyAddressComplement()
    {

    }

    /**
     * Test attribute "address_country"
     */
    public function testPropertyAddressCountry()
    {

    }

    /**
     * Test attribute "address_neighbourhood"
     */
    public function testPropertyAddressNeighbourhood()
    {

    }

    /**
     * Test attribute "address_number"
     */
    public function testPropertyAddressNumber()
    {

    }

    /**
     * Test attribute "address_postal_code"
     */
    public function testPropertyAddressPostalCode()
    {

    }

    /**
     * Test attribute "address_reference"
     */
    public function testPropertyAddressReference()
    {

    }

    /**
     * Test attribute "address_state"
     */
    public function testPropertyAddressState()
    {

    }

    /**
     * Test attribute "address_street"
     */
    public function testPropertyAddressStreet()
    {

    }

    /**
     * Test attribute "birthdate"
     */
    public function testPropertyBirthdate()
    {

    }

    /**
     * Test attribute "blocked"
     */
    public function testPropertyBlocked()
    {

    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {

    }

    /**
     * Test attribute "certificate_url"
     */
    public function testPropertyCertificateUrl()
    {

    }

    /**
     * Test attribute "cnpj"
     */
    public function testPropertyCnpj()
    {

    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {

    }

    /**
     * Test attribute "cpf"
     */
    public function testPropertyCpf()
    {

    }

    /**
     * Test attribute "crt"
     */
    public function testPropertyCrt()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "features"
     */
    public function testPropertyFeatures()
    {

    }

    /**
     * Test attribute "ie"
     */
    public function testPropertyIe()
    {

    }

    /**
     * Test attribute "invoice_default_serial_number"
     */
    public function testPropertyInvoiceDefaultSerialNumber()
    {

    }

    /**
     * Test attribute "invoice_initial_number"
     */
    public function testPropertyInvoiceInitialNumber()
    {

    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {

    }

    /**
     * Test attribute "iugu_account_id"
     */
    public function testPropertyIuguAccountId()
    {

    }

    /**
     * Test attribute "logo_url"
     */
    public function testPropertyLogoUrl()
    {

    }

    /**
     * Test attribute "mobile_phone"
     */
    public function testPropertyMobilePhone()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "paused"
     */
    public function testPropertyPaused()
    {

    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {

    }

    /**
     * Test attribute "picture_url"
     */
    public function testPropertyPictureUrl()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "terms_of_use_version"
     */
    public function testPropertyTermsOfUseVersion()
    {

    }

    /**
     * Test attribute "treatment"
     */
    public function testPropertyTreatment()
    {

    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {

    }

}
