<?php
/**
 * MODEL871628Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * olist-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MODEL871628Test Class Doc Comment
 *
 * @category    Class */
// * @description MODEL871628
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MODEL871628Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MODEL871628"
     */
    public function testMODEL871628()
    {

    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {

    }

    /**
     * Test attribute "brand"
     */
    public function testPropertyBrand()
    {

    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "free_shipping"
     */
    public function testPropertyFreeShipping()
    {

    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {

    }

    /**
     * Test attribute "gtin"
     */
    public function testPropertyGtin()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "package_measures"
     */
    public function testPropertyPackageMeasures()
    {

    }

    /**
     * Test attribute "photos"
     */
    public function testPropertyPhotos()
    {

    }

    /**
     * Test attribute "prices"
     */
    public function testPropertyPrices()
    {

    }

    /**
     * Test attribute "product_code"
     */
    public function testPropertyProductCode()
    {

    }

    /**
     * Test attribute "product_measures"
     */
    public function testPropertyProductMeasures()
    {

    }

    /**
     * Test attribute "seller_id"
     */
    public function testPropertySellerId()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "stock"
     */
    public function testPropertyStock()
    {

    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {

    }

    /**
     * Test attribute "tax_informations"
     */
    public function testPropertyTaxInformations()
    {

    }

}
