<?php
/**
 * MODEL6c172dTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * olist-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MODEL6c172dTest Class Doc Comment
 *
 * @category    Class */
// * @description MODEL6c172d
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MODEL6c172dTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MODEL6c172d"
     */
    public function testMODEL6c172d()
    {

    }

    /**
     * Test attribute "availability_days"
     */
    public function testPropertyAvailabilityDays()
    {

    }

    /**
     * Test attribute "cancelation_reason"
     */
    public function testPropertyCancelationReason()
    {

    }

    /**
     * Test attribute "channel_slug"
     */
    public function testPropertyChannelSlug()
    {

    }

    /**
     * Test attribute "channel_store"
     */
    public function testPropertyChannelStore()
    {

    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {

    }

    /**
     * Test attribute "delivered_customer_date"
     */
    public function testPropertyDeliveredCustomerDate()
    {

    }

    /**
     * Test attribute "estimated_delivery_date"
     */
    public function testPropertyEstimatedDeliveryDate()
    {

    }

    /**
     * Test attribute "invoice_danfe_url"
     */
    public function testPropertyInvoiceDanfeUrl()
    {

    }

    /**
     * Test attribute "invoice_error_message"
     */
    public function testPropertyInvoiceErrorMessage()
    {

    }

    /**
     * Test attribute "invoice_id"
     */
    public function testPropertyInvoiceId()
    {

    }

    /**
     * Test attribute "invoice_issue_date"
     */
    public function testPropertyInvoiceIssueDate()
    {

    }

    /**
     * Test attribute "invoice_key"
     */
    public function testPropertyInvoiceKey()
    {

    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {

    }

    /**
     * Test attribute "invoice_serial_number"
     */
    public function testPropertyInvoiceSerialNumber()
    {

    }

    /**
     * Test attribute "invoice_source"
     */
    public function testPropertyInvoiceSource()
    {

    }

    /**
     * Test attribute "invoice_status"
     */
    public function testPropertyInvoiceStatus()
    {

    }

    /**
     * Test attribute "invoice_url"
     */
    public function testPropertyInvoiceUrl()
    {

    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "purchase_timestamp"
     */
    public function testPropertyPurchaseTimestamp()
    {

    }

    /**
     * Test attribute "seller_brand"
     */
    public function testPropertySellerBrand()
    {

    }

    /**
     * Test attribute "seller_email"
     */
    public function testPropertySellerEmail()
    {

    }

    /**
     * Test attribute "seller_id"
     */
    public function testPropertySellerId()
    {

    }

    /**
     * Test attribute "seller_name"
     */
    public function testPropertySellerName()
    {

    }

    /**
     * Test attribute "seller_order_history"
     */
    public function testPropertySellerOrderHistory()
    {

    }

    /**
     * Test attribute "shipment"
     */
    public function testPropertyShipment()
    {

    }

    /**
     * Test attribute "shipping_limit_date"
     */
    public function testPropertyShippingLimitDate()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "suspension_reason"
     */
    public function testPropertySuspensionReason()
    {

    }

}
