<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * olist-api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for itemsBySkuList
     *
     * .
     *
     */
    public function testItemsBySkuList()
    {

    }

    /**
     * Test case for productGroupsCreate
     *
     * .
     *
     */
    public function testProductGroupsCreate()
    {

    }

    /**
     * Test case for productGroupsDelete
     *
     * .
     *
     */
    public function testProductGroupsDelete()
    {

    }

    /**
     * Test case for productGroupsList
     *
     * .
     *
     */
    public function testProductGroupsList()
    {

    }

    /**
     * Test case for productGroupsPartialUpdate
     *
     * .
     *
     */
    public function testProductGroupsPartialUpdate()
    {

    }

    /**
     * Test case for productGroupsRead
     *
     * .
     *
     */
    public function testProductGroupsRead()
    {

    }

    /**
     * Test case for productGroupsUpdate
     *
     * .
     *
     */
    public function testProductGroupsUpdate()
    {

    }

    /**
     * Test case for productsCreate
     *
     * .
     *
     */
    public function testProductsCreate()
    {

    }

    /**
     * Test case for productsDelete
     *
     * .
     *
     */
    public function testProductsDelete()
    {

    }

    /**
     * Test case for productsList
     *
     * .
     *
     */
    public function testProductsList()
    {

    }

    /**
     * Test case for productsPartialUpdate
     *
     * .
     *
     */
    public function testProductsPartialUpdate()
    {

    }

    /**
     * Test case for productsRead
     *
     * .
     *
     */
    public function testProductsRead()
    {

    }

    /**
     * Test case for productsUpdate
     *
     * .
     *
     */
    public function testProductsUpdate()
    {

    }

    /**
     * Test case for sellerOrdersCreate
     *
     * .
     *
     */
    public function testSellerOrdersCreate()
    {

    }

    /**
     * Test case for sellerOrdersDelete
     *
     * .
     *
     */
    public function testSellerOrdersDelete()
    {

    }

    /**
     * Test case for sellerOrdersItemsList
     *
     * .
     *
     */
    public function testSellerOrdersItemsList()
    {

    }

    /**
     * Test case for sellerOrdersItemsRead
     *
     * .
     *
     */
    public function testSellerOrdersItemsRead()
    {

    }

    /**
     * Test case for sellerOrdersList
     *
     * .
     *
     */
    public function testSellerOrdersList()
    {

    }

    /**
     * Test case for sellerOrdersPartialUpdate
     *
     * .
     *
     */
    public function testSellerOrdersPartialUpdate()
    {

    }

    /**
     * Test case for sellerOrdersRead
     *
     * .
     *
     */
    public function testSellerOrdersRead()
    {

    }

    /**
     * Test case for sellerOrdersShipment
     *
     * .
     *
     */
    public function testSellerOrdersShipment()
    {

    }

    /**
     * Test case for sellerOrdersUpdate
     *
     * .
     *
     */
    public function testSellerOrdersUpdate()
    {

    }

    /**
     * Test case for sellerProductsCreate
     *
     * .
     *
     */
    public function testSellerProductsCreate()
    {

    }

    /**
     * Test case for sellerProductsDelete
     *
     * .
     *
     */
    public function testSellerProductsDelete()
    {

    }

    /**
     * Test case for sellerProductsHistoryList
     *
     * .
     *
     */
    public function testSellerProductsHistoryList()
    {

    }

    /**
     * Test case for sellerProductsHistoryRead
     *
     * .
     *
     */
    public function testSellerProductsHistoryRead()
    {

    }

    /**
     * Test case for sellerProductsList
     *
     * .
     *
     */
    public function testSellerProductsList()
    {

    }

    /**
     * Test case for sellerProductsPartialUpdate
     *
     * .
     *
     */
    public function testSellerProductsPartialUpdate()
    {

    }

    /**
     * Test case for sellerProductsRead
     *
     * .
     *
     */
    public function testSellerProductsRead()
    {

    }

    /**
     * Test case for sellerProductsUpdate
     *
     * .
     *
     */
    public function testSellerProductsUpdate()
    {

    }

    /**
     * Test case for sellersCreate
     *
     * .
     *
     */
    public function testSellersCreate()
    {

    }

    /**
     * Test case for sellersDelete
     *
     * .
     *
     */
    public function testSellersDelete()
    {

    }

    /**
     * Test case for sellersList
     *
     * .
     *
     */
    public function testSellersList()
    {

    }

    /**
     * Test case for sellersPartialUpdate
     *
     * .
     *
     */
    public function testSellersPartialUpdate()
    {

    }

    /**
     * Test case for sellersRead
     *
     * .
     *
     */
    public function testSellersRead()
    {

    }

    /**
     * Test case for sellersUpdate
     *
     * .
     *
     */
    public function testSellersUpdate()
    {

    }

    /**
     * Test case for statsRead
     *
     * .
     *
     */
    public function testStatsRead()
    {

    }

    /**
     * Test case for statsRead_0
     *
     * .
     *
     */
    public function testStatsRead0()
    {

    }

    /**
     * Test case for usersCreate
     *
     * .
     *
     */
    public function testUsersCreate()
    {

    }

    /**
     * Test case for usersDelete
     *
     * .
     *
     */
    public function testUsersDelete()
    {

    }

    /**
     * Test case for usersList
     *
     * .
     *
     */
    public function testUsersList()
    {

    }

    /**
     * Test case for usersPartialUpdate
     *
     * .
     *
     */
    public function testUsersPartialUpdate()
    {

    }

    /**
     * Test case for usersRead
     *
     * .
     *
     */
    public function testUsersRead()
    {

    }

    /**
     * Test case for usersUpdate
     *
     * .
     *
     */
    public function testUsersUpdate()
    {

    }

}
